;.rnew /data/USERS/V2/DATA/IDL/RAMI_MODEL_TESTER.pro
.r /home/morgaol/ROMC/IDL/RAMI_MODEL_TESTER.pro

set_plot,'NULL'
exp1=['ART01_NAC_IPP_000_00']

MEASLIST=['gonio']

USR_INDIR=['/data/USERS/V3/input/hmind/4SH/200215220346/DATA/']
REF_INDIR='/data/USERS/V3/DATA/REFERENCE_DATA/FORWARD/DEBUG/MetEOC/GOVAERTS/'
OUTDIR='/data/USERS/V3/input/hmind/4SH/200215220346/RESULT/'
VALEXPFILE='/data/USERS/V3/DATA/ROFC/ValidFiles/FORWARD/DEBUG/MetEOC/Valid_EXPERIMENTS_Types.txt'
VALMESFILE='/data/USERS/V3/DATA/ROFC/ValidFiles/FORWARD/DEBUG/MetEOC/Valid_MEASUREMENTS_Types.txt'
REFTAG='4SH_200215220346'
REFMODNM='METEOCREF'
MODELNM=['4SH']
WATERMRK='DEBUG'

exp=[exp1]


RAMI_MODEL_TESTER,exp,MEASLIST,MODELNM,watermark=WATERMRK,/prps,USR_INDIR=USR_INDIR,REF_INDIR=REF_INDIR,OUTDIR=OUTDIR,VALEXPFILE=VALEXPFILE,VALMESFILE=VALMESFILE,REFTAG=REFTAG,REFMODNM=REFMODNM,/rms,/nobwjpeg,/skill,/snr

exit
