;.r /home/robusmo/projects/ROMC/USERS_pyV2/CODE/IDL/RAMI_MODEL_TESTER.pro
.r /home/morgaol/ROMC/IDL/RAMI_MODEL_TESTER.pro

set_plot,'NULL'

exp1=['HOM13_DIS_PLA_RED_20']

MODELNM1=['FLIGHT','LESS']

MEASLIST=['brfpp']


MODELNM1=['FLIGHT','LESS']

USR_INDIR1=['/home/robusmo/projects/ROMC/USERS_pyV2/northpe/FLIGHT/270307111438/DATA/','/home/robusmo/projects/ROMC/USERS_pyV2/jianboqi/LESS/080618001930/DATA/']

USR_INDIR=[USR_INDIR1]

REF_INDIR='/home/robusmo/projects/ROMC/USERS_pyV2/DATA/REFERENCE_DATA/FORWARD/DEBUG/RAMI3/HOM/'
PYOUTDIR='/home/robusmo/projects/ROMC/USERS_pyV2/COMPARISON/210910145853/'
OUTDIR='/home/robusmo/projects/ROMC/USERS_pyV2/COMPARISON/210910145853/'

OUTDIR='/home/morgaol/jrcbox_staging/ROMC_Results/COMPARISON/210910145853/IDL/'
PYOUTDIR='/home/morgaol/jrcbox_staging/ROMC_Results/COMPARISON/210910145853/python/'

VALEXPFILE='/home/robusmo/projects/ROMC/USERS_pyV2/DATA/ROFC/ValidFiles/FORWARD/DEBUG/RAMI3/Valid_EXPERIMENTS_Types.txt'
VALMESFILE='/home/robusmo/projects/ROMC/USERS_pyV2/DATA/ROFC/ValidFiles/FORWARD/DEBUG/RAMI3/Valid_MEASUREMENTS_Types.txt'
REFTAG='4SAIL2_270307123919'
REFMODNM='ROMCREF'
WATERMRK='DEBUG'

exp=[exp1]
MODELNM=[MODELNM1]


RAMI_MODEL_TESTER,exp,MEASLIST,MODELNM,watermark=WATERMRK,/prps,USR_INDIR=USR_INDIR,REF_INDIR=REF_INDIR,OUTDIR=OUTDIR,VALEXPFILE=VALEXPFILE,VALMESFILE=VALMESFILE,REFTAG=REFTAG,REFMODNM=REFMODNM,enveloppe=[1.0,2.5,5.0],/rms,/nobwjpeg,/skill,/snr,/copyright

exit
